'use client';
import { useRef, useState } from 'react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { Download, ShieldCheck } from 'lucide-react';
interface SponsorPDFExportProps {
  campaignName: string;
  creatorHandle: string;
  peakCcv: number;
  avgCcv: number;
  duration: string;
}
export default function SponsorPDFExport({
  campaignName, creatorHandle, peakCcv, avgCcv, duration,
}: SponsorPDFExportProps) {
  const templateRef = useRef<HTMLDivElement>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const handleDownload = async () => {
    if (!templateRef.current || isGenerating) return;
    setIsGenerating(true);
    try {
      const canvas = await html2canvas(templateRef.current, {
        scale: 2, backgroundColor: '#ffffff', useCORS: true, logging: false,
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      const pageHeight = pdf.internal.pageSize.getHeight();
      const renderHeight = Math.min(pdfHeight, pageHeight);
      const renderWidth = (canvas.width * renderHeight) / canvas.height;
      const xOffset = (pdfWidth - renderWidth) / 2;
      pdf.addImage(imgData, 'PNG', xOffset, 0, renderWidth, renderHeight);
      pdf.save('livekit-sponsor-report.pdf');
    } catch (err) {
      console.error('Sponsor PDF export failed:', err);
    } finally {
      setIsGenerating(false);
    }
  };
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  return (
    <>
      <button
        onClick={handleDownload}
        disabled={isGenerating}
        className="flex items-center gap-2 rounded-lg bg-orange-500 px-3 py-1.5 text-[11px] font-semibold text-black shadow-[0_0_15px_rgba(249,115,22,0.35)] transition hover:bg-orange-400 disabled:cursor-not-allowed disabled:opacity-60"
      >
        <Download className="size-3.5" />
        {isGenerating ? 'GENERATING PDF...' : 'Download Sponsor PDF'}
      </button>
      <div className="absolute left-[-9999px] top-0">
        <div ref={templateRef} className="w-[800px] bg-white p-10 text-black">
          <p className="text-xs font-semibold tracking-[0.2em] text-gray-500">LIVEKIT SPONSOR REPORT</p>
          <h1 className="mt-2 text-3xl font-extrabold text-black">Sponsor Campaign Report</h1>
          <p className="mt-2 text-sm text-gray-600">{campaignName} | @{creatorHandle} | {generatedDate}</p>
          <div className="mt-6 flex items-center gap-2 rounded-lg border border-green-300 bg-green-100 px-4 py-3 text-sm font-semibold text-green-800">
            <ShieldCheck className="size-5" />
            <span>LiveKit Verified: Generated from live campaign telemetry</span>
          </div>
          <div className="mt-8 grid grid-cols-3 gap-4">
            <div className="rounded-lg border border-gray-200 bg-gray-50 p-5">
              <p className="text-[11px] font-bold tracking-wider text-gray-500">PEAK REACH</p>
              <p className="mt-2 text-3xl font-extrabold text-black">{peakCcv.toLocaleString()}</p>
              <p className="mt-1 text-xs text-gray-500">Peak CCV</p>
            </div>
            <div className="rounded-lg border border-gray-200 bg-gray-50 p-5">
              <p className="text-[11px] font-bold tracking-wider text-gray-500">AVG SUSTAINED CCV</p>
              <p className="mt-2 text-3xl font-extrabold text-black">{avgCcv.toLocaleString()}</p>
              <p className="mt-1 text-xs text-gray-500">Average CCV</p>
            </div>
            <div className="rounded-lg border border-gray-200 bg-gray-50 p-5">
              <p className="text-[11px] font-bold tracking-wider text-gray-500">TOTAL DURATION</p>
              <p className="mt-2 text-3xl font-extrabold text-black">{duration}</p>
              <p className="mt-1 text-xs text-gray-500">Stream length</p>
            </div>
          </div>
          <div className="mt-8 grid grid-cols-2 gap-4 text-sm text-black">
            <div><p className="text-xs font-bold text-gray-500">CAMPAIGN</p><p className="mt-1 font-semibold">{campaignName}</p></div>
            <div><p className="text-xs font-bold text-gray-500">CREATOR</p><p className="mt-1 font-semibold">@{creatorHandle}</p></div>
          </div>
          <p className="mt-8 text-[11px] text-gray-400">Generated by LiveKit Dashboard | {generatedDate} | livekit-sponsor-report.pdf</p>
        </div>
      </div>
    </>
  );
}
